---
#
# Tags by conventional commit prefix
#
documentation:
  - "LICENSE*"
  - "*.md"
  - "**.md"
ci:
  - ".github/*"
  - ".github/**"
  - ".yamllint"
test:
  - "packages/client/test/**"
  - "packages/contracts/test/**"
  - "packages/default-join-server/test/**"
  - "packages/join-server/test/**"
build:
  - ".gitignore"
  - "Makefile"
  - "release*.bash"
  - "packages/client/Makefile"
  - "packages/contracts/Makefile"
  - "packages/join-server/Makefile"
  - "package.json"
  - "package-lock.json"
  - "packages/client/package.js"
  - "packages/default-join-server/package.json"
  - "packages/thegraph-subgraph/package.json"
  - "packages/contracts/package.json"
#
# Tags per npm package and conventional commit scope.
#
contracts:
  - "packages/contracts/*"
  - "packages/contracts/**"
client:
  - "packages/client/*"
  - "packages/client/**"
join-server:
  - "packages/join-server/*"
  - "packages/join-server/**"
default-join-server:
  - "packages/default-join-server/*"
  - "packages/default-join-server/**"
thegraph-subgraph:
  - "packages/thegraph-subgraph/*"
  - "packages/thegraph-subgraph/**"
